input_dir: "" # Path to directory containing input MAGs
input_text_file: /home/users/t/trickovi/scratch/sourmash/assign_subspecies/51_1000_posthumgut/posthumgut_paths.txt  # Path to text file containing paths to input MAGs
format1: .fna # File extension of input MAGs
format2: .fna.gz # File extension of input MAGs

batch_size: 50 # Number of MAGs to process in one batch

specific_hashomes: /home/users/t/trickovi/scratch/sourmash/sourmash-hash-manipulation-21/51_1000_union/specific_hashomes.sbt.zip
kmer_len: 51 # k-mer length, has to be the same as for specific_hashomes
scaled: 1000 # scaling factor, has to be the same as for specific_hashomes


### RESOURCES ###
threads: 8 # Number of threads
mem_mb: 12000 # Memory in MB
time_min: 90 # Time in minutes
tmpdir: /scratch # Path to temporary directory
